--- 
- 
  hosts: localhost
  tasks: 
    - 
      backend_config: 
      bucket: "{{ s3_bucket }}"
      key: "{{ key }}"
      name: "Run the terraform scirpts"
      project_path: ./
      region: "{{ region }}"
      state: "{{ state }}"
      terraform: 
      variables_file: "{{ app_env }}.tfvars"
      workspace: "{{ app_env }}"
  vars: 
    app_env: dev
    key: terraform.tfstate
    region: ap-south-1
    s3_bucket: terraform-jenkins-2020
    state: present
